name: Deploy Excel to CSV Cloud Function

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

env:
  TERRAFORM_DIRECTORY: infra
  SOURCE_CODE_DIRECTORY: src

jobs:
  check-python-code:
    name: Check Code Errors
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: ${{ env.SOURCE_CODE_DIRECTORY }}
#   deploy-cloud-function:
#     name: Deploy Excel to CSV Cloud Function
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       # authenticate with gcloud
#       - name: Authenticate to Google Cloud
#         id: auth
#         uses: google-github-actions/auth@v1
#         with:
#           token_format: access_token
#           workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
#           service_account: ${{ secrets.SA_EMAIL }}

#       # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#       # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
#       - name: Terraform Init
#         run: terraform init
#         working-directory: ${{ env.TERRAFORM_DIRECTORY }}

#       # Generates an execution plan for Terraform
#       - name: Terraform Plan
#         run: terraform plan
#         working-directory: ${{ env.TERRAFORM_DIRECTORY }}
#         env:
#           TF_VAR_service_account_email: ${{ secrets.SA_EMAIL }}

#       # Builds or changes infrastructure
#       - name: Terraform Apply
#         run: terraform apply -auto-approve
#         working-directory: ${{ env.TERRAFORM_DIRECTORY }}
#         env:
#           TF_VAR_service_account_email: ${{ secrets.SA_EMAIL }}
